<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Coordenadas Maven do Projeto Auto-Delver -->
    <groupId>com.nicolas</groupId>
    <artifactId>auto-delver</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
        <!-- Forca codificacao UTF-8 para evitar problemas de caracteres em diferentes SOs -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Configura a release para compilar nativamente em Java 21 -->
        <maven.compiler.release>21</maven.compiler.release>
    </properties>

    <build>
        <plugins>
            <!-- Plugin padrao de compilacao do Maven configurado para o Java 21 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>